### ISSUE TITLE
GUI doesn't fully shown

### ISSUE THREAD

**Issue by Jakeukalane** [db0/Lucid-Creations#32]
The GUI doesn't fully shown (too big) for my screen, it doesn't automatically change of size when resizing the window too. 

If I detach the panel, it got more shown but that is not optimal. GUI should automatically adjust.

I am using Manjaro Linux.

https://archive.ph/Jnu8N/06ebb220b29989123ae926d185be60dcab14b034.png

**Comment by db0** [comment]
I have tried to make it adjust, but naturally it needs a bit more work. I've been busy with other areas but I plan to improve this part.

**Comment by db0** [comment]
what is your resolution btw?

**Comment by Jakeukalane** [comment]
1366 x 768 but this problem I think can be present in a number of different resolutions. If is in the plan them I am satisfied. Can you add me to any "feature enhancement" ticket you open in the future about this (if so)?
thanks!

**Comment by db0** [comment]
Is it better with the new UI?

**Comment by xaihuome** [comment]
I downloaded v1.3.0 and it still has this problem. My resolution is also 1366 x 768

**Comment by Jakeukalane** [comment]
Still happens to me, although I found a workaround (for me) by moving the window with alt+f7.

**Comment by Jakeukalane** [comment]
Doesn't happen any more @db0

**Comment by db0** [comment]
Good to hear!
