### ISSUE TITLE
Bad URL. Please contact the developer of this add-on

### ISSUE THREAD

**Issue by Hashassin** [db0/Lucid-Creations#48]
since yesterday when updating godot lucid-creations i am getting this error constantly. i've only been able to receive results two or three times after fairly non-stop attempts for two days now, and am just waiting in cue, watching process, and then getting this error, repeatedly. at present, the tool has become unusable for me. i didn't see anywhere else to report this so i'm leaving it here.

**Comment by db0** [comment]
Were you using a different model than stable_diffusion? How long were you waiting until you got that error?

**Comment by db0** [comment]
There is a chance this will happen if we get a bad worker. If this still perists, try using trusted workers only and use basic stable_diffusion. See if this improves things

**Comment by Hashassin** [comment]
i've been trying it with every available model, trying single pic results instead of multiples, reducing size to minimum resolution, giving myself a new api key, etc. i shall give "trusted workers only" a go and see if that helps. 

thanks for the quick reply, and all the development. this has become my favourite toy of late, and it's able to produce some great results with fiddling. the new models are very interesting, just keeps getting better and better.

**Comment by Hashassin** [comment]
oh, and the wait time is of course dependent on settings and time of day, but i'd say anywhere between 20 minutes and an hour per result. sometimes i get lucky and the horde isn't very busy and i can crank out sets of 20 every five or ten minutes. 
k

**Comment by Hashassin** [comment]
trusted sources doesn't seem to be helping. i've just completed several runs and all ended with "bad url, contact dev"

**Comment by db0** [comment]
That doesn't make any sense. I just tried at Anonoymous and got 4 images back in 20 seconds. Are you using text2img or img2img?

**Comment by db0** [comment]
Can you try a simple prompt like "Godot Engine" and uncheck NSFW? I can't imagine why your requests are expiring like this. Ensure your model is set to stable_diffusion

**Comment by Hashassin** [comment]
running the prompt "godot engine" on generalist stable diffusion, with NSFW set to "off" and trusted workers "on", 256x256 resolution did indeed generate 5 results quickly with no error. as to the question of text2img vs img2img, i've been using both back and forth, but for this test it was simply text2img.

**Comment by Hashassin** [comment]
512 x512 also seems to be working okay. seems like it was something in the settings, but not sure what. the only change i can see is that "archer" is not showing up under models anymore? so maybe that had something to do with it? i did try using that model a few times, though i have been rotating through all of them, especially the newer ones to see what they can do.

**Comment by db0** [comment]
No that just means no worker is serving that model at the moment. 

I have to imagine it was something with your worker.
