### ISSUE TITLE
Cannot save on default folder when filename too long

### ISSUE THREAD

**Issue by demkom58** [db0/Lucid-Creations#51]
The error appears when pressing on `Save Image` button.

```
ERROR: Can't save PNG at path: 'user:///k_euler_a_30_A_digital_illustration_of_a_magic_fantasy_library_with_giant_tree__4k__detailed__trendi/4042689418__A_digital_illustration_of_a_magic_fantasy_library_with_giant_tree__4k__detailed__trendin.png'.
   at: save_image (drivers/png/resource_saver_png.cpp:56) - Condition "err" is true. Returned: err
ERROR: File must be opened before use.
   at: store_string (core/bind/core_bind.cpp:2182) - Condition "!f" is true.
```

I have tried to execute app with administrator privileges and here is enough space on disk.
My OS: Windows 10, 21H2

Edit:
Ok, I got it. The error occurs due too long file name.

**Comment by db0** [comment]
Can you try to change to file save folder?

**Comment by demkom58** [comment]
> Can you try to change to file save folder?

Yeah, I have tried save it to `C:/lc/` folder and it works too. In default folder it doesn't save if file has long name. Would be nice if it was possible to store only seed in names.

**Comment by db0** [comment]
Ye I think I'm going to switch to that approach due to windows BS. Thanks
