### ISSUE TITLE
UX: Lacking download redirection alternative link

### ISSUE THREAD

**Issue by mryellow** [db0/Lucid-Creations#61]
https://dbzer0.itch.io/lucid-creations/download/eyJleHBpcmVzIjoxNjY5NzYwMzMxLCJpZCI6MTcwNjQ3Nn0%3d.IVnoXhk%2fAPe4hJcHcFnbey11OmU%3d

> Thanks for downloading Lucid Creations - Stable Diffusion GUI without GPU by db0. You can find more from the same creator on their page: [db0](https://dbzer0.itch.io/). The download should start momentarily. If it doesn't, check your popup blocker.

No alternative download link provided.

**Comment by db0** [comment]
Sorry, what alternative download link are you looking for?

**Comment by mryellow** [comment]
It seems there might be a javascript redirect of some sort involved. Was failing until I disabled uMatrix entirely.

Usually pages provide a "Click here if your download fails to start" anchor tag fall-back.

**Comment by db0** [comment]
Ah I don't know that, this is all itch.io internals. I am just using their service
